# -*- coding: utf-8 -*-
"""notebook_s3_ex2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wkj-GKEWPR31cxkHnfDHzDbOJ0JOMArx

# LAB 3: Natural Language Generation
"""

!git clone https://github.com/elenipapadopulos/NLP_LAB3_Datasets.git

!pip install transformers

"""## Exercises

### Ex. 1: build a trigram model with backoff

In this exercise we are going to build a trigram model, implementing a back-off strategy.

Let's compute the unigram and bigram models.
"""

import nltk
nltk.download('punkt_tab')
nltk.download('brown') # import the Brown corpus from NLTK
nltk.download('punkt') # import tokenizer
import math

from nltk.corpus import brown

sentences = brown.sents()[:10000]
tokenized_corpus = []

for sentence in sentences:
  tokens = nltk.word_tokenize(' '.join(sentence))

  tokens = ['<s>'] + tokens + ['</s>']

  tokenized_corpus.extend(tokens)

from collections import Counter, defaultdict
from nltk import ngrams

unigram = list(ngrams(tokenized_corpus, 1))

unigram_count = Counter(unigram) # computes the occurrences

"""**Ex.1.1** Let's start by computing the unigram distribution: we already have the unigram counts, so what's left to do is normalizing them."""

## Ex 1.1

## compute the total number of tokens

#
total_tokens = sum(unigram_count.values())


## create a unigram model dictionary
## key: word
## value: probability


unigram_model = {word[0]: count / total_tokens for word, count in unigram_count.items()}

w1 = 'there'
print(f"{w1} -> {unigram_model[w1]}")

"""Compute the bigram model in the following cell.

### Compute bigrams
"""

from nltk import bigrams

# Generate bigram counts and model
bi_grams = list(bigrams(tokenized_corpus))
bigram_counts = Counter(bi_grams)
bigram_model = defaultdict(lambda: defaultdict(lambda: 0))

for (w1, w2), count in bigram_counts.items():
    # Normalize by the unigram count of the first word
    bigram_model[w1][w2] = count / unigram_count[(w1,)]

"""As we are working with trigrams, it is important to make sure that have two `<s>` at the beginning of the sentence to be able to estimate the first word."""



tokenized_corpus_tri = []
for sentence in sentences:

  tokens = nltk.word_tokenize(' '.join(sentence))

  tokens = ['<s>', '<s>'] + tokens + ['</s>']

  tokenized_corpus_tri.extend(tokens)

"""We can compute now our trigrams, using the `trigram` function."""

from nltk import trigrams

trigram = list(trigrams(tokenized_corpus_tri))

# let's define the trigram model as a dictionary of dictionaries
trigram_model = defaultdict(lambda: defaultdict(lambda: 0))

"""**Ex 1.2.**: Compute co-occurrences counts.
Note that the dictionary `trigram_model` takes as input a tuple of words as you can see from the example in the cell.
"""

## Ex 1.2

## compute trigram counts

#
for w1, w2, w3 in trigram:
    trigram_model[(w1, w2)][w3] += 1
#

w1_w2 = ('there', 'were')
print(f"{w1_w2} -> {dict(trigram_model[w1_w2])}")

"""**Ex 1.3** Compute trigram probabilities by normalizing counts."""

## Ex 1.3

## compute trigram probabilities


for context in trigram_model:
    total_count = sum(trigram_model[context].values())

    for w3 in trigram_model[context]:

        trigram_model[context][w3] /= total_count


w1_w2 = ('there', 'were')
print(f"{w1_w2} -> {dict(trigram_model[w1_w2])}")

"""**Ex. 1.4** Implement the back-off function.

The function backoff should take as input the trigram, bigram and unigram models, the context words $w_1$ and $w_2$ and a discount factor $\alpha$ and it should return the next word $w_3$ to be generated and its probabilty.


Recall: for each $w_3$, if $P(w_3 \mid w_1, w_2)$ is not in the trigram model, then use $P(w_3 \mid w_2)$ (discounted by $\alpha$). If there is no $P(w_3 \mid w_2)$, then use $P(w_3)$ (discounted by $\alpha^2$).

"""

def backoff(trigram_model, bigram_model, unigram_model, w1, w2, alpha):

  # remove the <s> token from the unigram model before using it for backoff:
  # it is the most probable token and will be chosen if algorithm backs off to unigrams
  vocab = {w: p for w, p in unigram_model.items() if w != '<s>'}

  # given the context w1_w2, use backoff to find word with the highest probability:
  # for every w in vocabulary, check if p(w|w1_w2) exists, otherwise back off to bigrams
  # if there is no p(w|w2), then back off to unigram probability
  next_word = None
  max_prob = -1.0

  for w3 in vocab:
      if w3 in trigram_model[(w1, w2)]:
          prob = trigram_model[(w1, w2)][w3]
      elif w3 in bigram_model[w2]:
          prob = alpha * bigram_model[w2][w3]
      else:
          prob = (alpha ** 2) * vocab[w3]

      if prob > max_prob:
          max_prob = prob
          next_word = w3

  # use the computed trigram, bigram and unigram models

  # greedy decoding: you should return next_word, probability
  return next_word, max_prob

"""The function can be used now during generation, as you can see in the following cell."""

def backoff_generation(trigram_model, bigram_model, unigram_model, seed_words, alpha, max_lenght=15):

  w1, w2 = seed_words
  generated_words = [w1, w2]

  log_prob_sum = 0.0
  N = 0

  for _ in range(max_lenght):

    next_word, probability = backoff(trigram_model, bigram_model, unigram_model, w1, w2, alpha)

    generated_words.append(next_word)
    log_prob_sum += math.log(probability)
    N += 1

    w1, w2 = w2, next_word

  perplexity = math.exp(-log_prob_sum / N) if N > 0 else float('inf')

  return ' '.join(generated_words), perplexity

seed = ("well", "if")
alpha = 0.4
generated_sentence, perplexity = backoff_generation(trigram_model, bigram_model, unigram_model, seed, alpha)
print("Generated sentence:", generated_sentence)
print("Perplexity:", perplexity)

seed = ("there", "was")
generated_sentence, perplexity = backoff_generation(trigram_model, bigram_model, unigram_model, seed, alpha)
print("Generated sentence:", generated_sentence)
print("Perplexity:", perplexity)

"""### Ex. 2: typo detection"""

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
import matplotlib.pyplot as plt
import math
import pandas as pd

"""In this exercise, you are asked to use a Large Language Model (GPT2) to detect typos in sentences.

Let's start by uploading our dataset: it is a collection of 52 sentences of various type, half of which are grammatically sound.
"""

df = pd.read_csv("/content/NLP_LAB3_Datasets/typo_dataset1.csv")

"""You can see that these sentences contain typos (so spelling errors or missing letters) but also grammatical errors like omophones."""

print(f"Text: {df['text'][26]} \nLabel: {df['label'][26]} (Typo)")

print(f"Text: {df['text'][21]} \nLabel: {df['label'][21]} (Correct)")

"""Let's import GPT2."""

device =  "cuda:0" if torch.cuda.is_available() else "cpu"

model_name = "gpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name).to(device)

"""We will use the token \<s> as our marker for the beginning of a sentence. First, we need to add it to the tokenizer’s vocabulary, then set it as the bos_token, and finally, resize the model’s embedding size.

"""

bos_token = "<s>"
tokenizer.add_tokens([bos_token])
tokenizer.bos_token = bos_token
model.resize_token_embeddings(len(tokenizer))

"""**Ex 2.1** Write a function that returns the log-probability assigned to each generated token.

You can use the `get_next_word_probs` function as a reference, but remember that this time we’re focusing on the distribution of tokens **within** the sentence, rather than the probability distribution of the next token. You can follow the comments we left in the box to guide you in the implementation.

"""

def get_token_logprobs(sentence):

    ## tokenize the sentence, compute the output and retrieve logits


    inputs = tokenizer(tokenizer.bos_token + sentence, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model(**inputs)

    logits = outputs.logits

    ## remember: logits.shape is (1, sen_len, model_size])
    ## remove the logits relative to the last token: we are not interested in next token generation
    ## expected shape: (sen_len, model_size) (suggestion: use squeeze))
    #
    shift_logits = logits[0, :-1, :].squeeze()

    ## retrieve the indices (input_ids) of the sentence
    ## hint: remove the input_id relative to the bos
    ## expected shape: (sen_len)
    indices = inputs["input_ids"][0, 1:]

    ## compute log-probabilities
    log_probs = torch.nn.functional.log_softmax(shift_logits, dim=-1)

    ## retrieve the probabilities of the tokens
    token_logprobs = log_probs[range(len(indices)), indices]

    ## convert input ids to tokens to obtain a list of tokens

    tokens = tokenizer.convert_ids_to_tokens(indices)

    return tokens, token_logprobs.tolist()

"""**Ex 2.2** Write a function that returns the cumulative log-probability **up to each token** in a sentence, using the probabilities computed before.

Remind that, as we are considering log-probabilities, you should **sum** the individual log-probabilities of each individual token.

Hint: you could return a list of elements like (w, cumulative_probability_up_to_w)

"""

def get_cumulative_token_logprobs(sentence):

    tokens, token_logprobs = get_token_logprobs(sentence)

    # write your code here
    cumulative_logprobs = []
    current_sum = 0
    for token, logprob in zip(tokens, token_logprobs):
        current_sum += logprob
        cumulative_logprobs.append((token, current_sum))

    return cumulative_logprobs

"""**Ex. 2.3** Write a function that determines whether a sentence contains typos or not based on the difference of log-probabilities of consecutive tokens/words. The hypothesis is that a significant drop in probability between consecutive tokens may indicate that the model did not expect that token, potentially signaling a typo.

To implement this, we can define a threshold: if the difference between the log-probabilities of consecutive tokens exceeds this threshold, we can assume the sentence likely contains a typo.

The function should take as input the sentence to be analyzed and the threshold to apply for detection and it should return 0 if the sentence is flagged as potentially containing typos or	1 if the sentence is considered correct.

In the function you should confront consecutive log-probabilities and check whether, for at least one pair, their difference is above the set threshold: in that case, classify the whole sentence as incorrect.
"""

def detect_typos(sentence, threshold=5):

    word_logprobs = get_cumulative_token_logprobs(sentence)

    # write your code here
    individual_probs = []
    for i in range(len(word_logprobs)):
        if i == 0:
            individual_probs.append(word_logprobs[i][1])
        else:
            individual_probs.append(word_logprobs[i][1] - word_logprobs[i-1][1])

    label = 1
    for i in range(1, len(individual_probs)):
        if (individual_probs[i-1] - individual_probs[i]) > threshold:
            label = 0
            break

    return label

"""**Ex 2.4** Test your function experimenting with different thresholds.
Select the best threshold on the whole data and report the accuracy in the Moodle.

You should achieve an accuracy higher than 0.70.
"""

correct = 0

for i, row in df.iterrows():

  sentence, label = row.iloc[1], row.iloc[2]

  pred = detect_typos(sentence, threshold=7.2)

  if label == pred:
    correct += 1

print(f"Accuracy: {correct/len(df)}")

"""**Error Analysis**: in this exercise, we exploited the probability distribution of a Large Language Model to detect typos.
Did you notice any linguistic or grammatical feature that make detection more accurate? Do you think relying solely on threshold-based differences in log-probabilities is sufficient or should we use a more sophisticated and complete system? Write your comments in the box below.

## Moodle submission

Extract the code to run exercise 1 and 2 from the notebook as a .py file (you might have to add some initial import instructions). Make sure the code runs and computes the accuracy correctly. Upload the code on the activity "Lab assignment 3" on the Moodle of the course. In the comment box on Moodle report your accuracy and your comments related to the error analys (box right above)
"""
